/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#151d19",
        "on-primary-fixed-variant": "#17503b",
        "on-error-container": "#93000a",
        "inverse-primary": "#9ad3b7",
        "surface-dim": "#d3dcd6",
        "surface": "#f3fcf5",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-variant": "#dce5de",
        "on-primary": "#ffffff",
        "background": "#f3fcf5",
        "secondary-fixed": "#ffdbcd",
        "secondary-fixed-dim": "#ffb597",
        "outline-variant": "#c0c9c2",
        "on-secondary-fixed": "#360f00",
        "tertiary": "#761300",
        "surface-container-low": "#edf6ef",
        "inverse-surface": "#2a322e",
        "primary": "#04432f",
        "primary-fixed": "#b5efd2",
        "secondary": "#914b2b",
        "surface-tint": "#326852",
        "on-primary-fixed": "#002115",
        "tertiary-fixed-dim": "#ffb4a4",
        "primary-fixed-dim": "#9ad3b7",
        "error": "#ba1a1a",
        "on-tertiary-container": "#ffb2a1",
        "error-container": "#ffdad6",
        "outline": "#707973",
        "on-tertiary-fixed": "#3d0600",
        "surface-container": "#e7f0e9",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#404944",
        "surface-container-highest": "#dce5de",
        "surface-bright": "#f3fcf5",
        "on-tertiary-fixed-variant": "#8b1901",
        "tertiary-container": "#9b250b",
        "primary-container": "#245b45",
        "on-error": "#ffffff",
        "secondary-container": "#fda27c",
        "inverse-on-surface": "#eaf3ec",
        "tertiary-fixed": "#ffdad3",
        "on-surface": "#151d19",
        "surface-container-high": "#e2eae4",
        "on-secondary-container": "#773618",
        "on-primary-container": "#98d1b5",
        "on-secondary-fixed-variant": "#743416"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-lg": "1rem",
        "gutter": "0.75rem",
        "margin": "1rem",
        "space-xl": "1.5rem",
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "label-lg": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "title-md": ["16px", { "lineHeight": "22px", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
